package com.sixpay.payment.domain.policy;

public enum ResultIntentDecision {
    NONE,
    IMMEDIATE_PROCESSING,
    IMMEDIATE_REJECTED,
    IMMEDIATE_FAILED,
    IMMEDIATE_POSTED_PENDING_TFJ,
    IMMEDIATE_REVERSAL_REQUIRED,
    FINAL_TREASURY_INTEGRATED,
    REVERSAL_REVERSED,
    REVERSAL_REJECTED_OR_NOT_ALLOWED
}
