package com.sixpay.payment.infrastructure.tresorpay;

public enum TresorPayErrorCode {
    INVALID_REQUEST,
    MISSING_HEADER,
    INVALID_IDEMPOTENCY_KEY,
    INVALID_CALLBACK_URL,
    INVALID_BENEFICIARY_TOTAL,
    AUTHENTICATION_REQUIRED,
    INVALID_ACCESS_TOKEN,
    INVALID_CLIENT_CERTIFICATE,
    PARTNER_NOT_AUTHORIZED,
    PARTNER_IDENTITY_MISMATCH,
    SCOPE_NOT_GRANTED,
    CALLBACK_URL_NOT_ALLOWED,
    API_KEY_INVALID,
    REPLAY_DETECTED,
    REQUEST_TIMESTAMP_INVALID,
    IDEMPOTENCY_KEY_CONFLICT,
    END_TO_END_ID_CONFLICT,
    PAYMENT_INITIATION_IN_PROGRESS,
    RATE_LIMIT_EXCEEDED,
    BANKING_SERVICE_UNAVAILABLE,
    PAYMENT_PROCESSING_UNAVAILABLE
}
