package com.sixpay.integration.error;
public enum ExternalErrorCategory {
    AUTHENTICATION, AUTHORIZATION, VALIDATION, BUSINESS_REJECTION,
    NOT_FOUND, CONFLICT, RATE_LIMIT, TIMEOUT, OUTCOME_UNKNOWN,
    UNAVAILABLE, PROTOCOL, INVALID_RESPONSE, INTEGRITY, CONFIGURATION, INTERNAL
}
