package com.sixpay.payment.api;

public enum PaymentQueryStatus {
    RECEIVED,
    PENDING_CONFIRMATION,
    AUTHORIZATION_CHECKING,
    BANKING_VERIFICATION_PENDING,
    FUNDS_CONTROL_PENDING,
    TREASURY_ACCOUNT_RESOLUTION_PENDING,
    APPROVED_FOR_POSTING,
    POSTING_PENDING,
    POSTING_OUTCOME_UNKNOWN,
    DEBIT_CONFIRMED,
    POSTED_PENDING_TFJ,
    REVERSAL_REQUIRED,
    REVERSAL_PENDING,
    REVERSAL_OUTCOME_UNKNOWN,
    REJECTED,
    FAILED,
    TREASURY_INTEGRATED,
    REVERSED
}
